
stages:
  - build
    script:
      - curl -s -L https://github.com/getzola/zola/releases/download/v0.5.1/zola-v0.5.1-x86_64-unknown-linux-gnu.tar.gz | sudo tar xvzf - -C /usr/local/bin
      - zola build
  - name: deploy
    if: branch = master
    skip-cleanup: true
    script:
      - bash deploy.sh
